-- USERS: Basic profile and validity
CREATE TABLE IF NOT EXISTS USERS (
    USERNAME TEXT PRIMARY KEY,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    STATUS TEXT CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) DEFAULT 'ACTIVE',
    VALIDFROM DATE NOT NULL,
    VALIDTO DATE NOT NULL
);

-- USERS_SESSION: Tracks login status
CREATE TABLE IF NOT EXISTS USERS_SESSION (
    USERNAME TEXT PRIMARY KEY,
    LOGIN_STATUS TEXT CHECK (LOGIN_STATUS IN ('LOGGED_IN', 'LOGGED_OUT')) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

-- USERS_ROLES: Permissions per user
CREATE TABLE IF NOT EXISTS USERS_ROLES (
    USERNAME TEXT PRIMARY KEY,
    USER_TYPE TEXT CHECK (USER_TYPE IN ('ADMIN', 'TRADER', 'VIEWER')) NOT NULL,
    NSE_FNO TEXT CHECK (NSE_FNO IN ('Y', 'N')) DEFAULT 'N',
    NSE_STOCK TEXT CHECK (NSE_STOCK IN ('Y', 'N')) DEFAULT 'N',
    MCX_FNO TEXT CHECK (MCX_FNO IN ('Y', 'N')) DEFAULT 'N',
    ALERTS TEXT CHECK (ALERTS IN ('Y', 'N')) DEFAULT 'N',
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

-- USERS_AUTH: Secure password storage (bcrypt hash)
CREATE TABLE IF NOT EXISTS USERS_AUTH (
    USERNAME TEXT PRIMARY KEY,
    PASSWORD_HASH TEXT NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

-- CONFIG: Per-instrument-type scan config
CREATE TABLE IF NOT EXISTS CONFIG (
    INSTRUMENT_TYPE TEXT PRIMARY KEY,
    INTERVAL TEXT NOT NULL,
    VOLUME_THRESHOLD REAL NOT NULL
);

-- SIGNAL TABLES (optional, for separate dashboards)
CREATE TABLE IF NOT EXISTS signals_stock_fno (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT,
    signal_type TEXT,
    signal_time TEXT,
    open REAL, high REAL, low REAL, close REAL,
    volume REAL, volume_delta REAL
);

CREATE TABLE IF NOT EXISTS signals_index_fno (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT,
    signal_type TEXT,
    signal_time TEXT,
    open REAL, high REAL, low REAL, close REAL,
    volume REAL, volume_delta REAL
);